// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Outbox.Api.Data;

#nullable disable

namespace Outbox.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260210175429_ConfigureMessageDeliveryFKs")]
    partial class ConfigureMessageDeliveryFKs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Outbox.Api.Entities.DeliveryAttempt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AttemptedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("ConsideredRetryable")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OutboxDeliveryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("OutboxDeliveryId", "AttemptedAtUtc");

                    b.ToTable("DeliveryAttempts");
                });

            modelBuilder.Entity("Outbox.Api.Entities.OutboxDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastAttemptUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("NextAttemptUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OutboxMessageId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubjectKey")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("OutboxMessageId", "SubscriptionId")
                        .IsUnique();

                    b.HasIndex("Status", "NextAttemptUtc");

                    b.HasIndex("TenantId", "Status", "NextAttemptUtc");

                    b.HasIndex("TenantId", "SubscriptionId", "Status");

                    b.ToTable("OutboxDeliveries");
                });

            modelBuilder.Entity("Outbox.Api.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraHeadersJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SignatureSecretId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SignatureVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("TenantId", "CreatedAtUtc");

                    b.HasIndex("TenantId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("TenantId", "SubjectKey");

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("Outbox.Api.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxConcurrency")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "IsActive");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("Outbox.Api.Entities.DeliveryAttempt", b =>
                {
                    b.HasOne("Outbox.Api.Entities.OutboxDelivery", "OutboxDelivery")
                        .WithMany("Attempts")
                        .HasForeignKey("OutboxDeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OutboxDelivery");
                });

            modelBuilder.Entity("Outbox.Api.Entities.OutboxDelivery", b =>
                {
                    b.HasOne("Outbox.Api.Entities.OutboxMessage", "OutboxMessage")
                        .WithMany("Deliveries")
                        .HasForeignKey("OutboxMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Outbox.Api.Entities.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OutboxMessage");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Outbox.Api.Entities.OutboxDelivery", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("Outbox.Api.Entities.OutboxMessage", b =>
                {
                    b.Navigation("Deliveries");
                });
#pragma warning restore 612, 618
        }
    }
}
